Dangling _test_pageBot object after IDE closes causes showElement() to fail. Create a new object each time for now. To reproduce issue: Start IDE, attempt to [Find] using bad locator, close IDE, start IDE again, attempt to [Find] again using bad locator. You will notice the second time around, the error message is different: 'TypeError: locator.startsWith is not a function' .
git-svn-id: http://selenium.googlecode.com/svn@4545 07704840-8298-11de-bf8c-fd130f914ac9